kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: python:3.10-bullseye
  commands:
  - echo hello
  - echo world

- name: docker
  image: plugins/docker
  settings:
    username: valentinvolkov
    password: uHFVJNFl0
    repo: valentinvolkov/scrapy
    tags: latest