kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: valentinvolkov/scrapy
    tags: 1.1
  when:
    branch:
      - main
    event:
      - push