version: "1"
services:
  scrapy:
    image: scrapy-test
    container_name: scrapy
    volumes:
      - ./spiders:/code/scrapy_basic/scrapy_basic/spiders
    environment:
      - SPIDER_NAME=test
      - HTTP_POST_AUTH_TOKEN=bf2da524cd02dd452fcfefc5e5ad11ad1f68126c
      - HTTP_POST_URL=http://127.0.0.1:8000/zen_articles/
    command: bash
