version: "1"
services:
  scrapy:
    image: valentinvolkov/scrapy:1.1
    container_name: scrapy
    volumes:
      - ./spiders:/code/scrapy_basic/scrapy_basic/spiders
    environment:
      - SPIDER_NAME=test
      - AUTH_TOKEN=test
      - HTTP_POST_URL=https://content-bulk.online/zen_article/